"""Central constants for the phishing detection platform."""

from __future__ import annotations

DEFAULT_TRUSTED_DOMAINS = {
    "github.com",
    "google.com",
    "microsoft.com",
    "apple.com",
    "amazon.com",
    "facebook.com",
    "twitter.com",
    "instagram.com",
    "linkedin.com",
    "youtube.com",
    "netflix.com",
    "reddit.com",
    "wikipedia.org",
    "stackoverflow.com",
    "paypal.com",
    "chase.com",
    "wellsfargo.com",
    "bankofamerica.com",
    "anthropic.com",
    "openai.com",
    "cloudflare.com",
    "amazonaws.com",
    "docker.com",
    "render.com",
    "railway.app",
    "vercel.com",
    "netlify.com",
    "pypi.org",
    "npmjs.com",
    "medium.com",
    "dev.to",
    "gitlab.com",
    "bitbucket.org",
    "heroku.com",
    "digitalocean.com",
    "linode.com",
    "stripe.com",
    "twilio.com",
    "sendgrid.com",
    "mongodb.com",
    "firebase.com",
    "notion.so",
    "figma.com",
    "canva.com",
    "trello.com",
    "slack.com",
    "zoom.us",
    "dropbox.com",
    "onedrive.com",
    "x.com",
    "onlinesbi.sbi.bank.in",
}

RISKY_TLDS = {
    "tk",
    "ml",
    "ga",
    "cf",
    "gq",
    "top",
    "xyz",
    "club",
    "online",
    "site",
    "work",
    "party",
    "live",
    "click",
    "link",
    "win",
    "loan",
    "download",
}

BRANDS = ("sbi", "paypal", "microsoft", "apple", "amazon", "google")
SUSPICIOUS_KEYWORDS = (
    "verify",
    "secure",
    "confirm",
    "credential",
    "suspend",
    "login",
    "password",
    "account",
    "bank",
)
